framework:
    default_locale: fr
    set_locale_from_accept_language: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
            - en
        providers:
