
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-11.4}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
      MARIADB_USER: ${MARIADB_USER:-root}
    #healthcheck:
    #  test: ["CMD", "pg_isready", "-d", "${MARIADB_DATABASE:-app}", "-U", "${MARIADB_USER:-root}"]
    #  timeout: 5s
    #  retries: 5
    #  start_period: 60s
    volumes:
      - database_data:/var/lib/mariadb:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysbql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
