
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: app
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: app
      MARIADB_USER: root
    healthcheck:
      test: ["CMD", "mariadb", "-h", "127.0.0.1", "-papp", "app", "-e", "SELECT 1"]
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - database_data:/var/lib/mariadb:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysbql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
