POST https://127.0.0.1:8000/en/admin?crudAction=editInPlace&crudControllerFqcn=App%5CController%5CAdmin%5CBoothCrudController&entityId=16770e01-f7bc-43c6-926c-0b6cca46e397
Accept: text/html
Referer: https://127.0.0.1:8000/en/admin/booth
Origin: https://127.0.0.1:8000
Cookie: REMEMBERME=App.Entity.User%3AYWRtaW4~%3A1746992742%3A-LM91Ey5UyZl2H-5IxNA8brEn9YY3djFksELbudgi4Q~l0dYnzsfdb9S4xtpSIObExnrS7fO9Tuot9TFKiohe6o~; main_auth_profile_token=528ae2; PHPSESSID=3b66f911354bef73b72b6a9b851ee796
Content-Type: application/json

{
    "maxNumberOfParticipants": "6"
}
