name: PHP

on: [push]

jobs:
    build:
        name: Conventionist PHP

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'

            - name: Cache composer dependencies
              uses: actions/cache@v4
              with:
                  path: "~/.composer/cache/files"
                  key: "composer-${{ hashFiles('**/composer.lock') }}"
                  restore-keys: "composer-"

            - name: 'Install Symfony CLI'
              run: |
                curl -sS https://get.symfony.com/cli/installer | bash
                mv ~/.symfony5/bin/symfony /usr/local/bin/symfony

            - name: 'Install the project'
              run: |
                make install

            - name: '🚀 Tests'
              run: make test

            - name: '🚀 Coverage'
              run: make coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  files: ./.phpunit.cache/coverage.xml
                  token: ${{ secrets.CODECOV_TOKEN }}
